const quotes = [
    "Meow!",
    "Focus is the key.",
    "One thing at a time.",
    "You are doing great.",
    "Deep work mode: ON.",
    "Stay hydrated!",
    "Keep moving forward.",
    "Consistency is likely.",
    "Small steps, big progress.",
    "Don't forget to breathe.",
    "Zone in.",
    "Simplify.",
    "Execute.",
    "Build momentum.",
    "The Penthouse, 1 Feline Supremacy Plaza, Meow York, MY 69420 (Center of the Fucking Universe)",
    "Have you tried turning it off and on again?",
    "It's not DNS, There's no way it's DNS, It was DNS...",
    "0 days since it was DNS.",
    "sudo shitdown now",
    "Stop refreshing, you're supposed to be focusing right now!",
    "You're not lazy, you're just tired.",
    "I'm not procrastinating, I'm just doing other things.",
    "I'll do it tomorrow.",
    "I'm just resting my eyes.",
    "I'm just taking a break.",
    "I'm just stretching my legs.",
    "I'm just getting a snack.",
    "I'm just getting a drink.",
    "I'm just getting a coffee.",
    "I'm just getting a tea.",
    "I'm just getting a water.",
    "I'm just getting a juice.",
    "I'm just getting a soda.",
    "I'm just getting a beer.",
    "I'm just getting a wine.",
    "I'm just getting a cocktail.",
    "I'm just getting a spirit.",
    "I'm just getting a liqueur.",
    "I'm just getting a cordial.",
    "pacman is a good package manager, but yay is even better.",
    "I use Arch btw.",
    "sudo rm -rf / --no-preserve-root",
    "Got milk?",
    "I'm not lazy, I'm just energy efficient.",
    "I'm not procrastinating, I'm just in creative mode.",
    "I'm not lazy, I'm just in deep thought mode.",
    "I'm not lazy, I'm just in strategic planning mode.",
    "I'm not lazy, I'm just in optimization mode.",
    "I'm not lazy, I'm just in efficiency mode.",
    "I'm not lazy, I'm just in productivity mode.",
    "I'm not lazy, I'm just in focus mode.",
    "I'm not lazy, I'm just in flow mode.",
    "I'm not lazy, I'm just in zen mode.",
    "I'm not lazy, I'm just in recharge mode.",
    "I'm not lazy, I'm just in power saving mode.",
    "I'm not lazy, I'm just in sleep mode.",
    "I'm not lazy, I'm just in hibernation mode.",
    "I'm not lazy, I'm just in hyperfocus mode.",
    "A good mouse is a Deadmau5.",
    "You didn't fuck up, you just found a bug.",
    "Cat got your tongue?",
    "Catnip is just meowijuana for cats.",
    "I'm not kitten you, this is a purrfect pun.",
    "I'm feline good today.",
    "Both RuneScape and Old School RuneScape are good games, fight me.",
    "Book recommendation: W*nkernomics A Deep-Dive into Workplace Bullsh*ttery by James Schloeffel & Charles Firth.",
    "Hey! Relax, guy. Relax!",
    "Screw you guys, I'm going home!",
    "Respect my authoritah!",
    "Don't forget to bring a towel!",
    "Drugs are bad, m'kay?",
    "Oh my God, they killed Kenny! You bastards!",
    "I'm not fat, I'm big boned!",
    "I'm super cereal.",
    "They took our jobs!",
    "Whateva! I do what I want!",
    "Step 1: Collect underpants. Step 2: ? Step 3: Profit.",
    "I thought this was America!",
    "I'm not your friend, buddy!",
    "I'm not your buddy, guy!",
    "I'm not your guy, friend!",
    "Simpsons did it!",
    "You're a towel!",
    "No, Kitty, this is my pot pie!",
    "Nobody expects the Spanish Inquisition!",
    "It's just a flesh wound.",
    "And now for something completely different.",
    "I fart in your general direction!",
    "Ni!",
    "What is the airspeed velocity of an unladen swallow?",
    "Your mother was a hamster and your father smelt of elderberries!",
    "Always look on the bright side of life.",
    "Strange women lying in ponds distributing swords is no basis for a system of government.",
    "He's not the Messiah, he's a very naughty boy!",
    "I'm not dead yet!",
    "She turned me into a newt! ... I got better.",
    "Run away! Run away!",
    "This is an ex-parrot!",
    "Help, help, I'm being repressed!",
    "Bring out your dead!",
    "I'm a lumberjack and I'm OK, I sleep all night and I work all day.",
    "My hovercraft is full of eels.",
    "What have the Romans ever done for us?",
    "Blessed are the cheesemakers.",
    "Are you suggesting coconuts migrate?",
    "It's only a model.",
    "A path! A path!",
    "It's only a tiny, thin, little wafer.",
    "Better get a bucket.",
    "The machine that goes 'ping'!",
    "Every sperm is sacred.",
    "I think it's a bit early to start imposing roles on it, don't you?",
    "Can we have your liver then?",
    "Try and be nice to people, avoid eating fat, read a good book every now and then, and try and live together in peace and harmony with people of all creeds and nations.",
    "Was it the salmon mousse?",
    "I'll have the lot!",
    "Just remember that you're standing on a planet that's evolving and revolving at nine hundred miles an hour.",
    "And pray that there's intelligent life somewhere up in space, 'cause there's bugger all down here on Earth.",
    "And now, Part I: The Miracle of Birth.",
    "It's fun to charter an accountant and sail the wide accountancy!",
    "A tiger? In Africa?",
    "I'm not procrastinating, I'm just on a side quest.",
    "404: Focus not found.",
    "Look, a squirrel!",
    "I have 57 tabs open and I don't know where the music is coming from.",
    "Everything is a drum if you're bored enough.",
    "I came, I saw, I forgot what I was doing.",
    "This is fine.",
    "Hello there!",
    "General Kenobi!",
    "It's over Anakin, I have the high ground!",
    "I don't like sand.",
    "UNLIMITED POWER!",
    "I am the Senate.",
    "Execute Order 66.",
    "This is where the fun begins.",
    "Another happy landing.",
    "Is it a bird? Is it a plane? No, it's a distraction!",
    "The first rule of Focus Club is: you do not talk about Focus Club.",
    "There is no spoon.",
    "This is the way.",
    "I have spoken.",
    "Never tell me the odds!",
    "It's a trap!",
    "Do or do not, there is no try.",
    "The ability to speak does not make you intelligent.",
    "Don't Panic.",
    "I love deadlines. I love the whooshing noise they make as they go by.",
    "Time is an illusion. Lunchtime doubly so.",
    "So long, and thanks for all the fish.",
    "Space is big. Really big. You just won't believe how vastly, hugely, mind-bogglingly big it is.",
    "The ships hung in the sky in much the same way that bricks don't.",
    "For a moment, nothing happened. Then, after a second or so, nothing continued to happen.",
    "The Answer to the Ultimate Question of Life, The Universe, and Everything is 42.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Would it save you a lot of time if I just gave up and went mad now?",
    "Curiously enough, the only thing that went through the mind of the bowl of petunias as it fell was Oh no, not again."
];

document.addEventListener('DOMContentLoaded', () => {
    const quoteEl = document.getElementById('quote-display');
    if (quoteEl) {
        const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
        quoteEl.innerText = randomQuote;
    }
});
